#include <vector>
#include <chrono>
#include "utils.hpp"
#ifdef USE_RCPP_OUTPUT
#include <Rcpp.h>
using namespace Rcpp;
#else
#endif
#include <string>
#include <vector>
#include <chrono>
#include <regex>
#include "utils.hpp"

#ifdef USE_RCPP_OUTPUT
#include <Rcpp.h>
using namespace Rcpp;
#else
#endif

// -------------------------------------------------------------------
// helper: extract all integers after patterns like:
//   size=123;
//   "total_count":123
//   "count":123
//
// returns sum of all detected values
// -------------------------------------------------------------------
static size_t extract_size_fields(const std::string& header) {
    size_t sum = 0;

    // match size=123;
    {
        std::regex rgx_size("size=([0-9]+)");
        std::smatch m;
        auto s = header;
        while (std::regex_search(s, m, rgx_size)) {
            sum += std::stoul(m[1].str());
            s = m.suffix();
        }
    }
    /*
    // match "total_count":123
    {
        std::regex rgx_total("\"total_count\"\\s*:\\s*([0-9]+)");
        std::smatch m;
        auto s = header;
        while (std::regex_search(s, m, rgx_total)) {
            sum += std::stoul(m[1].str());
            s = m.suffix();
        }
    }

    // match "count":123   (for per-sample)
    {
        std::regex rgx_count("\"count\"\\s*:\\s*([0-9]+)");
        std::smatch m;
        auto s = header;
        while (std::regex_search(s, m, rgx_count)) {
            sum += std::stoul(m[1].str());
            s = m.suffix();
        }
    }
    */
    return sum;
}

// -------------------------------------------------------------------
//' Count sequence records and summarize size fields from metadata blocks
//'
//' This function counts the number of sequence records in a FASTA or FASTQ
//' file, which may be plain text or gzip-compressed. If the header of a record
//' contains metadata blocks generated by previous processing steps such as
//' `"denoise"` or `"stat"`, the function extracts numeric size information from
//' fields such as \code{size=}, \code{"total_count"}, or per-sample \code{"count"}
//' entries. All extracted values are summed and reported separately for each
//' module.
//'
//' @param input_file (character) path to the input FASTA or FASTQ file. The
//'   file may be plain text or gzip-compressed (suffix \code{.gz}).
//'
//' @return
//' Invisibly returns \code{NULL}. The console output includes:
//' \itemize{
//'   \item total number of sequence records,
//'   \item sum of all \code{size=} values (if present),
//'   \item sum of all size values extracted from `"denoise"` blocks,
//'   \item sum of all size values extracted from `"stat"` blocks,
//'   \item time elapsed during processing.
//' }
//' @export
// [[Rcpp::export]]
void count_records(std::string input_file) {

    input_file = expandTilde(input_file);
    auto start_time = std::chrono::system_clock::now();

    bool is_fastq = isFastqFile(input_file);
    bool is_gz = isGzFile(input_file);

    FILE* fp_plain = nullptr;
    gzFile fp_gz = nullptr;

    if (is_gz) {
        fp_gz = gzopen(input_file.c_str(), "rb");
        if (!fp_gz) {
            CERR << "[Error] Failed to open gzip file: " << input_file << std::endl;
            return;
        }
    }
    else {
        fp_plain = fopen(input_file.c_str(), "rb");
        if (!fp_plain) {
            CERR << "[Error] Failed to open file: " << input_file << std::endl;
            return;
        }
    }

    show_time("Counting records and extracting size fields...");

    size_t record_count = 0;
    size_t total_size_from_headers = 0;

    FastqRecord rec;

    while (readRec(is_gz, fp_plain, fp_gz, rec, is_fastq)) {
        record_count++;

        // Extract size values from header (rec.id)
        total_size_from_headers += extract_size_fields(rec.id);
    }

    if (fp_plain) fclose(fp_plain);
    if (fp_gz) gzclose(fp_gz);

    auto end_time = std::chrono::system_clock::now();
    std::chrono::duration<double> elapsed = end_time - start_time;

    show_time("Total records: " + std::to_string(record_count));
    show_time("Sum of size fields: " + std::to_string(total_size_from_headers));
    show_time("", 1, elapsed.count());
}
/*
void count_records(  std::string& input_file) {
	input_file = expandTilde(input_file);
	auto start_time = std::chrono::system_clock::now();
	bool is_fasq = isFastqFile(input_file);
	bool is_gz = isGzFile(input_file);
	FastqRecord rec;
	std::vector<FastqRecord> rec_v;
	FILE* fp_plain = nullptr;
	gzFile fp_gz = nullptr;
	if (is_gz) fp_gz = gzopen(input_file.c_str(), "rb");
	else fp_plain = fopen(input_file.c_str(), "rb");
	while (readRec(is_gz, fp_plain, fp_gz, rec, is_fasq)) {
		rec_v.push_back(rec);
	}
	if (is_gz) gzclose(fp_gz);
	else fclose(fp_plain);
	show_time("Counting...");
	auto end_time = std::chrono::system_clock::now();
	std::chrono::duration<double> elapsed = end_time - start_time;
	show_time("Total records: " + std::to_string(rec_v.size()));
	show_time("", 1, elapsed.count());

}
*/