
#' Convert FASTA file with embedded JSON metadata into a long- or wide-format table
#'
#' This function reads a FASTA file generated by the METAeDNA pipeline, extracts
#' sequence-level metadata from embedded JSON blocks (e.g., `"stat"` or
#' `"denoise"`), and converts the information into a tidy table. Both sequence
#' identifiers and per-PCR abundance/status metadata are retained. The output is
#' a wide-format table with one row per unique sequence and one column per
#' experiment–sample pair.
#'
#' @param fas_file (character) path to the input FASTA file. The file must
#'   contain JSON metadata blocks in the header produced by earlier steps such
#'   as \code{pairend}, \code{unique}, or \code{denoise}.
#'
#' @param threads (integer) number of parallel workers used for parsing JSON
#'   blocks. When \code{threads > 1}, parallelization is handled through
#'   \pkg{furrr} and \pkg{future}.
#'
#' @details
#' The function performs the following steps:
#' \itemize{
#'   \item Reads the FASTA file using \code{Biostrings::readDNAStringSet()}.
#'   \item Extracts the JSON metadata block from each header. This block may
#'         originate from:
#'         \itemize{
#'           \item \code{"stat"} (output of the dereplication module), or
#'           \item \code{"denoise"} (output of the denoising module).
#'         }
#'   \item Parses per-experiment and per-sample counts and status labels.
#'         If \code{"denoise"} → \code{"by_sample"} is present, it is used;
#'         otherwise the \code{"stat"} block is parsed.
#'   \item Constructs a long-format table with columns:
#'         \code{experiment}, \code{sample}, \code{count}, \code{status},
#'         \code{ID}, and \code{SEQ}.
#'   \item Computes total counts per sequence–experiment pair.
#'   \item Produces a wide-format abundance/status table using
#'         \code{tidyr::pivot_wider()}, where each sample contributes a
#'         \code{count_*} and \code{status_*} column.
#'   \item Assigns a unique sequence identifier of the form
#'         \code{SEQ_0000001}, \code{SEQ_0000002}, etc.
#' }
#'
#' @return
#' A wide-format \code{tibble} containing merged sequence metadata. The table
#' includes:
#' \itemize{
#'   \item \code{experiment}: experiment name,
#'   \item \code{ID}: original sequence identifier,
#'   \item \code{SEQ}: the nucleotide sequence as a character string,
#'   \item \code{SEQ_ID}: a newly assigned unified sequence identifier,
#'   \item \code{count_*}: per-sample abundance values,
#'   \item \code{status_*}: per-sample labels such as \code{"head"},
#'         \code{"internal"}, or \code{"singleton"},
#'   \item \code{total_count}: total abundance per sequence–experiment pair.
#' }
#'
#' @importFrom purrr map2_dfr map_dfr
#' @importFrom jsonlite fromJSON
#' @importFrom Biostrings readDNAStringSet
#' @importFrom dplyr mutate as_tibble group_by reframe left_join
#'   rename_with ungroup relocate cur_group_id
#' @importFrom furrr future_map2 future_map2_dfr furrr_options
#' @importFrom tidyr pivot_wider
#' @importFrom stringr str_extract str_remove str_replace_all str_detect
#'
#' @examples
#' \dontrun{
#' tbl <- fasta_to_table("denoised.fasta", threads = 4)
#' head(tbl)
#' }
#'
#' @export
fasta_to_table <- function(fas_file, threads = 1){
  if(threads == 1){
    plan(sequential)
  }else{
    plan(multisession, workers = threads)
  }

  dna_set <- readDNAStringSet(fas_file)
  seq_vec <- as.character(dna_set)
  temp_name <- names(seq_vec)
  names(seq_vec) <- str_remove(names(dna_set), ";size.*")

  seq_id <- names(seq_vec)
  json_block_text <- str_extract(temp_name,"[{].*")
  all_seq_df <- suppressWarnings(future_map2_dfr(json_block_text, seq_id, function(js_txt, sid) {
    if (is.na(js_txt) || js_txt == "") return(NULL)
    js <- fromJSON(js_txt)

    #  JSON without block
    if (is.null(js$denoise$by_sample)) {

      df <- map_dfr(js$stat$exp, function(expt){
        map_dfr(expt$samples, as_tibble, .id = "sample")
      }, .id = "experiment")
    }else{
      # experiment → sample → count/status
      df <- map_dfr(js$denoise$by_sample, function(expt)
        map_dfr(expt, as_tibble, .id = "sample"), .id = "experiment")
      }
#browser()
    df %>%
      mutate(ID = sid,
            SEQ = seq_vec[[sid]]) %>%
      return()
  }))
  sum_reads <- all_seq_df %>% group_by(SEQ,experiment ) %>% reframe(total_count = sum(count))
  # show_time("The denoise block was not found! Unique data imformation used.")
  by_sample_df <- all_seq_df %>%
    pivot_wider(
      names_from  = sample,
      values_from = c(count, status),
      values_fill = list(count = 0, status = NA),
      names_sep = "_"
    ) %>%
    # rename_with(~ str_remove(., "^count_"), starts_with("count_")) %>%
    group_by(SEQ) %>%
    mutate(SEQ_ID = paste0("SEQ_",str_pad(cur_group_id(),width = 7, side = "left", pad = "0"))) %>%
    ungroup() %>%
    left_join(sum_reads,by = join_by(SEQ,experiment )) %>% relocate(experiment, ID, SEQ,  total_count)
  return(by_sample_df)
}

# Format Genbank fasta to dada2 style ---------------

#' Format GenBank FASTA records to the DADA2 reference format
#'
#' This function converts a GenBank-style FASTA file into a DADA2-compatible
#' reference FASTA, where sequence names follow the standardized
#' \code{Kingdom;Phylum;Class;Order;Family;Genus;Species} taxonomy format.
#' Accession numbers are parsed from the original FASTA headers, taxonomic
#' identifiers are retrieved from a local SQL database, and complete taxonomy
#' strings are constructed for use in DADA2 reference workflows.
#'
#' @param input_fasta_file (character) path to the input FASTA file. The file
#'   should contain GenBank-style headers from which accession numbers can be
#'   extracted.
#'
#' @param output_fasta_file (character) path to the output FASTA file written
#'   in DADA2 reference format. Sequence headers are replaced by taxonomy
#'   strings with spaces converted to underscores.
#'
#' @param sql_path (character) path to a SQLite database containing NCBI
#'   taxonomy tables. This database must support accession → taxid mapping
#'   and taxid → full taxonomy queries used by \code{get_taxid()} and
#'   \code{get_taxonomy()}.
#'
#' @param show_elapsed (logical) whether to report elapsed time using
#'   \code{show_time()}. If \code{TRUE}, a timer is initialized at the beginning
#'   of the function and printed on exit.
#'
#' @details
#' The function performs the following steps:
#' \itemize{
#'   \item Reads all sequences using \code{Biostrings::readDNAStringSet()}.
#'   \item Extracts accession numbers from GenBank-style headers. For legacy
#'         \code{gi|} records, accession numbers are parsed from the embedded
#'         \code{"gb|ACC|"} field.
#'   \item Queries a local SQL taxonomy database to obtain:
#'         \itemize{
#'           \item taxonomic identifiers using \code{get_taxid()},
#'           \item full taxonomy ranks using \code{get_taxonomy()}.
#'         }
#'   \item Constructs the DADA2-style taxonomy string:
#'         \code{kingdom;phylum;class;order;family;genus;species}.
#'   \item Replaces original sequence names with the constructed taxonomy
#'         strings (spaces are replaced by underscores).
#'   \item Writes the formatted sequences to \code{output_fasta_file} using
#'         \code{Biostrings::writeXStringSet()}.
#' }
#'
#' @return
#' Invisibly returns \code{NULL}. The output FASTA file contains the original
#' sequences with headers rewritten in DADA2 taxonomy format.
#'
#' @importFrom dplyr mutate as_tibble group_by reframe left_join rename_with ungroup relocate
#' @importFrom stringr str_extract str_remove str_detect str_replace_all
#' @importFrom Biostrings readDNAStringSet writeXStringSet
#'
#' @examples
#' \dontrun{
#' format_to_dada(
#'   input_fasta_file = "genbank_raw.fasta",
#'   output_fasta_file = "dada2_ref.fasta",
#'   sql_path = "taxonomy.sqlite",
#'   show_elapsed = TRUE
#' )
#' }
#'
#' @export
format_to_dada <- function(input_fasta_file, output_fasta_file, sql_path, show_elapsed = T){
  start_time <- Sys.time()
  if(show_elapsed) on.exit(show_time(sec = Sys.time() - start_time , mode =1))
  raw_seq <- readDNAStringSet(input_fasta_file)

  seq_acc <- raw_seq %>% names() %>% str_remove(" .*")
  if(str_detect(seq_acc, "^gi") %>% all){
    seq_acc <- seq_acc %>% str_extract("gb[|].*[|]") %>% str_remove("gb[|]") %>% str_remove("[|]")
  }
  taxonomy_id <- get_taxid(sql_path = sql_path, seq_acc, show_elapsed = F)

  query_res <- get_taxonomy(sql_path = sql_path, tax_ids = taxonomy_id$taxid %>% unique, dereplicate = F, show_elapsed = F)

  taxonomy_data <- left_join(taxonomy_id, query_res, by = join_by(taxid == query_tax_id)) %>%
    mutate(dada_name = paste(kingdom, phylum, class, order, family, genus, species, sep = ";"))
  names(raw_seq) <- taxonomy_data$dada_name %>% str_replace_all(" ", "_")
  show_time("Formatting names...")
  writeXStringSet(raw_seq, output_fasta_file)
}


