# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count sequence records and summarize size fields from metadata blocks
#'
#' This function counts the number of sequence records in a FASTA or FASTQ
#' file, which may be plain text or gzip-compressed. If the header of a record
#' contains metadata blocks generated by previous processing steps such as
#' `"denoise"` or `"stat"`, the function extracts numeric size information from
#' fields such as \code{size=}, \code{"total_count"}, or per-sample \code{"count"}
#' entries. All extracted values are summed and reported separately for each
#' module.
#'
#' @param input_file (character) path to the input FASTA or FASTQ file. The
#'   file may be plain text or gzip-compressed (suffix \code{.gz}).
#'
#' @return
#' Invisibly returns \code{NULL}. The console output includes:
#' \itemize{
#'   \item total number of sequence records,
#'   \item sum of all \code{size=} values (if present),
#'   \item sum of all size values extracted from `"denoise"` blocks,
#'   \item sum of all size values extracted from `"stat"` blocks,
#'   \item time elapsed during processing.
#' }
#' @export
count_records <- function(input_file) {
    invisible(.Call(`_METAeDNA_count_records`, input_file))
}

#' Demultiplex FASTQ reads using primer and tag information
#'
#' This function assigns each FASTQ read to a sample based on matching forward
#' and reverse primers, as well as optional tag sequences. For each read, the
#' identified experiment, sample, tag, and primer mismatches are recorded in a
#' `"demultiplex"` JSON block appended to the FASTA header.
#'
#' @param fastq_file (character) path to the input FASTQ file. The file may be
#'   plain text or gzip-compressed (suffix \code{.gz}).
#'
#' @param primer_table (character) path to a CSV/TSV file containing primer and
#'   tag definitions. This table must include experiment names, sample names,
#'   forward and reverse primers, and optional tag sequences.
#'
#' @param identified_output (character) path to the output file that receives
#'   reads successfully assigned to a sample. If \code{compress_output = TRUE}
#'   or the file name ends with \code{.gz}, the file is gzip-compressed.
#'
#' @param unidentified_output (character) path to the output file for reads
#'   that cannot be matched to any sample based on the specified primers and
#'   tags. Compression behavior is identical to \code{identified_output}.
#'
#' @param n_threads (integer) number of parallel threads used for matching
#'   primers and tags. When OpenMP support is available, multiple threads
#'   accelerate demultiplexing.
#'
#' @param with_tag (logical) if \code{TRUE}, tag sequences must be present
#'   and matched in addition to primers. If \code{FALSE}, only primer matching
#'   is performed.
#'
#' @param compress_output (logical) if \code{TRUE}, write all output files in
#'   gzip format regardless of output file name suffix.
#'
#' @param compress_level (integer, between 0 and 9) gzip compression level
#'   applied when writing compressed output.
#'
#' @param primer_mismatch (integer) maximum number of mismatches allowed when
#'   matching primers. Tag matching does not allow mismatches.
#'
#' @param return_list (logical) if \code{TRUE}, the function returns summary
#'   information as an R list instead of writing only to disk. In the current
#'   implementation this argument is reserved and output is written to disk.
#'
#' @return
#' Invisibly returns \code{NULL}. Identified reads are written to
#' \code{identified_output}, whereas unmatched reads are written to
#' \code{unidentified_output}. Each identified read receives a `"demultiplex"`
#' JSON block in the header containing experiment, sample, tag, primer matches,
#' and mismatch counts.
#' @export
demultiplex <- function(fastq_file, primer_table, identified_output, unidentified_output, n_threads = 4L, with_tag = TRUE, compress_output = FALSE, compress_level = 6L, primer_mismatch = 3L, return_list = FALSE) {
    invisible(.Call(`_METAeDNA_demultiplex`, fastq_file, primer_table, identified_output, unidentified_output, n_threads, with_tag, compress_output, compress_level, primer_mismatch, return_list))
}

#' Denoise FASTA sequences using abundance and local sequence similarity
#'
#'
#' For each sequence, a `"denoise"` JSON block is appended to the header
#' summarizing per-PCR status and counts, and the overall
#' \code{size=} and \code{"total_count"} fields are updated to match the
#' retained counts. Output can be written either uncompressed or gzip-compressed.
#'
#' @param input_fasta (character) string; path to the input FASTA file. The file
#'   may be plain text or gzip-compressed (suffix \code{.gz}).
#' @param output_fasta (character )string; path to the output FASTA file. If the
#'   file name ends with \code{.gz} or \code{compress_output = TRUE}, the
#'   output is gzip-compressed.
#' @param sequence_min_L (integer); minimum sequence length to retain. Sequences
#'   shorter than this threshold are discarded before denoising.
#' @param sequence_max_L (integer); maximum sequence length to retain. Sequences
#'   longer than this threshold are discarded before denoising.
#' @param min_count (integer) minimum total read count (summed over all PCRs)
#'   required to keep a sequence. Sequences with total counts below this
#'   threshold are removed before graph construction.
#' @param threshold (double) scalar in (0,1); abundance ratio threshold used
#'   to direct edges in the neighbor graph. For a pair of neighboring
#'   sequences with counts \code{high} and \code{low}, an edge
#'   \code{high -> low} is created only if \code{low/high < threshold}. These
#'   directed edges are then used to classify \code{"head"}, \code{"internal"},
#'   and \code{"singleton"} sequences per PCR.
#' @param n_threads (integer) number of parallel threads used for neighbor
#'   search and labeling. When OpenMP is available, values greater than 1
#'   enable multi-threaded computation; otherwise this argument is ignored.
#' @param max_diff  (integer >= 0) maximum number of substitutions allowed
#'   between two sequences for them to be considered neighbors. Setting
#'   \code{max_diff = 1} restricts neighbors to Hamming distance 1 (plus any
#'   allowed indels via \code{max_indel}).
#' @param max_indel (integer >= 0) maximum absolute indel size (in base pairs)
#'   allowed between two sequences for them to be considered neighbors.
#'   \code{max_indel = 0} restricts neighbors to equal length; \code{max_indel = 1}
#'   additionally allows single-base insertions/deletions.
#' @param keep_internal (logical) if \code{FALSE}, sequences that are labeled
#'   \code{"internal"} in all PCRs are removed from the output. For sequences
#'   that are kept, any per-PCR entries with status \code{"internal"} may be
#'   dropped from the per-PCR statistics.
#' @param keep_previous_stat (logical) if \code{TRUE}, the existing JSON block
#'   in the header (typically produced by previous steps such as \code{unique})
#'   is preserved and the new `"denoise"` block is appended to it. If
#'   \code{FALSE}, the old statistics block is discarded and the header is
#'   rebuilt to contain only the sequence identifier and the new `"denoise"`
#'   block (with updated \code{size=} and \code{"total_count"} fields).
#' @param compress_output (logical) if \code{TRUE}, the output FASTA is written
#'   as gzip regardless of the file name suffix.
#' @param compress_level (integer,between 0 and 9) gzip compression level passed
#'   to \code{gzopen()} when \code{compress_output} is enabled or the output
#'   file name ends with \code{.gz}. Higher values give better compression at
#'   the cost of slower writing.
#'
#' @return
#' Invisibly returns \code{NULL}. The main result is the FASTA file written to
#' \code{output_fasta}, where each header line has been updated to include a
#' `"denoise"` JSON block with per-PCR counts and status labels, together with
#' summary tallies of \code{"head"}, \code{"internal"}, and \code{"singleton"}
#' occurrences across all PCRs.
#' @details
#' For each PCR independently, sequences are first filtered by length and total
#' abundance thresholds. A local neighbor graph is then constructed by
#' connecting sequences that differ by at most a user-defined number of
#' substitutions (\code{max_diff}) and/or short indels (\code{max_indel}). Edges
#' are directed from higher-abundance sequences to lower-abundance sequences
#' when their abundance ratio satisfies the specified \code{threshold}. This
#' directed graph is used to classify sequences into three categories per PCR:
#' \code{"head"} (no outgoing edges), \code{"internal"} (receiving edges from
#' higher-abundance neighbors), and \code{"singleton"} (no neighbors). This algorithm was described by Boyer et. al.,(2016)
#'
#' @section Citations: Boyer, F., Mercier, C., Bonin, A., Le Bras, Y., Taberlet, P. and Coissac, E. (2016), obitools: a unix-inspired software package for DNA metabarcoding. Mol Ecol Resour, 16: 176-182. \url{https://doi.org/10.1111/1755-0998.12428}
#' @export
denoise <- function(input_fasta, output_fasta, sequence_min_L = 1L, sequence_max_L = 1000L, min_count = 1L, threshold = 0.05, n_threads = 32L, max_diff = 1L, max_indel = 0L, keep_internal = TRUE, keep_previous_stat = FALSE, compress_output = FALSE, enable_avx2 = TRUE, debug = FALSE, compress_level = 6L) {
    invisible(.Call(`_METAeDNA_denoise`, input_fasta, output_fasta, sequence_min_L, sequence_max_L, min_count, threshold, n_threads, max_diff, max_indel, keep_internal, keep_previous_stat, compress_output, enable_avx2, debug, compress_level))
}

#' Merge paired-end reads from FASTQ files
#'
#' This function merges paired-end reads from two FASTQ files by identifying
#' overlapping regions between read 1 and the reverse-complement of read 2.
#' Overlap length, mismatch allowance, and overlap scoring can be customized.
#'
#' @param fastq_1 (character) path to the FASTQ file containing read 1.
#'   The file may be plain text or gzip-compressed.
#' @param fastq_2 (character) path to the FASTQ file containing read 2.
#'   The file may be plain text or gzip-compressed.
#' @param out_file (character) path to the output FASTQ file containing merged
#'   paired-end reads. If \code{compress_output = TRUE} or the file name ends
#'   with \code{.gz}, the output is gzip-compressed.
#'
#' @param compress_level (integer, 0–9) gzip compression level passed to
#'   \code{gzopen()} when writing compressed output.
#'
#' @param min_overlap (integer) minimum overlap length required for merging
#'   two reads. Overlaps shorter than this threshold are not used.
#'
#' @param max_mismatches (integer) maximum number of mismatched bases allowed
#'   within the overlapping region between the two reads.
#'
#' @param compress_output (logical) if \code{TRUE}, write the output FASTQ file
#'   in gzip format regardless of the suffix of \code{out_file}.
#'
#' @param return_list (logical) if \code{TRUE}, the function returns results
#'   as an R list instead of writing to a file. In the current implementation,
#'   this argument is reserved and output is written to disk.
#'
#' @param lambda (double) penalty weight applied to mismatches during overlap
#'   scoring. This parameter controls the mismatch contribution to the overlap
#'   score returned by the algorithm.
#'
#' @param score_threshold (double) minimum overlap score required for accepting
#'   a merged read. Merged reads with scores below this threshold are discarded.
#'
#' @param n_threads (integer) number of parallel threads used for merging.
#'   When OpenMP is available, multi-threading accelerates overlap detection
#'   and merging within each processed batch.
#'
#' @param batch_size (integer) number of read pairs processed per batch.
#'   Larger batch sizes reduce I/O overhead but increase memory usage.
#'
#' @return
#' Invisibly returns \code{NULL}. The merged reads are written to
#' \code{out_file}, with each merged record containing updated sequence,
#' quality string, and a JSON block appended to the identifier summarizing
#' overlap size, mismatch count, and overlap score.
#' @export
pairend <- function(fastq_1, fastq_2, out_file, compress_level = 6L, min_overlap = 10L, max_mismatches = 5L, compress_output = FALSE, return_list = FALSE, lambda = 0.5, score_threshold = 0, n_threads = 4L, batch_size = 1000000L) {
    invisible(.Call(`_METAeDNA_pairend`, fastq_1, fastq_2, out_file, compress_level, min_overlap, max_mismatches, compress_output, return_list, lambda, score_threshold, n_threads, batch_size))
}

#' Collapse duplicate sequences in a FASTA/FASTQ file
#'
#' This function identifies all identical sequences in an input FASTA or FASTQ
#' file and collapses them into unique sequence entries. For each unique
#' sequence, the function aggregates the total read count and the per-PCR
#' (experiment–sample) counts derived from the input header metadata. The
#' resulting dereplicated FASTA file contains one record per unique sequence,
#' with an updated `"stat"` JSON block summarizing the merged counts and the
#' sequence length. If paired-end metadata was present (in a `"pairend"`
#' block), it is preserved in the output.
#'
#' @param input_fasta (character) path to the input FASTA or FASTQ file. The
#'   file may be plain text or gzip-compressed (suffix \code{.gz}).
#'
#' @param output_fasta (character) path to the dereplicated output FASTA file.
#'   If \code{compress_output = TRUE} or if the file name ends with \code{.gz},
#'   the file is written in gzip-compressed format.
#'
#' @param n_threads (integer) number of threads used for processing. When
#'   OpenMP support is available, multiple threads accelerate sequence hashing
#'   and merging.
#'
#' @param compress_output (logical) whether to write the output file in gzip
#'   format regardless of the suffix of \code{output_fasta}.
#'
#' @param compress_level (integer, between 0 and 9) gzip compression level used
#'   when writing compressed output.
#'
#' @param batch_size (integer) number of records to read and process per batch.
#'   Larger values reduce I/O overhead but require more memory.
#'
#' @details
#' Each input record is parsed into:
#' \itemize{
#'   \item the sequence identifier (prefix before any metadata block),
#'   \item optional \code{"pairend"} metadata block,
#'   \item optional experiment and sample identifiers contained in
#'         \code{"stat"} or previous pipeline modules.
#' }
#' The function maintains per-sequence counters:
#' \itemize{
#'   \item \code{total_count}: total occurrences of the same sequence,
#'   \item per-PCR counts: \code{exp → sample → count}.
#' }
#' After all batches are processed, unique sequences are written to the output
#' FASTA file. Each header contains:
#' \itemize{
#'   \item \code{size=}: total count of the sequence,
#'   \item a `"stat"` JSON block summarizing per-PCR counts,
#'   \item preserved `"pairend"` metadata when present.
#' }
#'
#' @return
#' Invisibly returns \code{NULL}. The dereplicated sequences are written to
#' \code{output_fasta}. Each output record includes updated counts, preserved
#' metadata, and a single representative sequence.
#' @export
dereplicate <- function(input_fasta, output_fasta, n_threads = 4L, compress_output = FALSE, compress_level = 6L, batch_size = 100000L) {
    invisible(.Call(`_METAeDNA_dereplicate`, input_fasta, output_fasta, n_threads, compress_output, compress_level, batch_size))
}

